import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { getServerSession } from "next-auth/next";
import NavMenu from "@/app/components/NavMenu";
import SessionProvider from "@/app/components/SessionProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Music-minus App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession();
  return (
    <html lang="en" data-theme="dark">
      <head>
        <script
          src="https://cdn.jsdelivr.net/npm/theme-change@2.0.2/index.js"
          defer
        ></script>
      </head>
      <body className={inter.className}>
        <SessionProvider session={session}>
          <main className="mx-auto max-w-6xl gap-2">
            <NavMenu />
            {children}
          </main>
        </SessionProvider>
      </body>
    </html>
  );
}
